language: node_js
node_js:
  - "12"
cache: yarn
jobs:
  include:
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add codecov lerna
script:
  - lerna bootstrap
  - cd packages/final-state
  - yarn build
  - yarn test
  - cd -
  - cd packages/final-state-logger
  - yarn build
  - yarn test
  - cd -
  - cd packages/final-state-rx
  - yarn build
  - yarn test
  - cd -
  - cd packages/react-final-state
  - yarn build
  - yarn test
  - cd -
after_success:
  - codecov
